apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: static-web-app
  template:
    metadata:
      labels:
        app: static-web-app
    spec:
      containers:
        - name: static-web-app
          image: my-docker-image:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-web-app-service
spec:
  selector:
    app: static-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
